In [1]:
import numpy as np

In [2]:
escalar = 5.679
vector = np.array([2,3])
matriz = np.array([[1,2],[3,4],[5,6]])

In [3]:
A = matriz * vector

In [4]:
B = matriz.dot(vector)

In [5]:
print(A)

[[ 2  6]
 [ 6 12]
 [10 18]]


In [6]:
print(B)

[ 8 18 28]


In [7]:
B = matriz.dot(vector)
C = np.dot(matriz, vector)
print(B)
print(C)

[ 8 18 28]
[ 8 18 28]


In [9]:
D = np.dot(vector, matriz)

ValueError: shapes (2,) and (3,2) not aligned: 2 (dim 0) != 3 (dim 0)