In [2]:
import numpy as np 

In [2]:
np.set_printoptions(suppress=True)
#redondea resultados

In [3]:
#Sistema de ecuaciones 1
#3x + y = 1
#2x + y = 1
#A x = b
#A = matriz de coeficientes
#x = vector de variables
#b = vector de resultados
#para encontrar el vector de variables x = (A^-1) . (b)
#Funciona si la matriz de coeficientes no es singular (determinante != 0)
A = np.array([[3,1], [2,1]])
print(A)

[[3 1]
 [2 1]]


In [4]:
b = np.array([[1],[1]])
print(b)

[[1]
 [1]]


In [5]:
inversa_A = np.linalg.inv(A)
print(inversa_A)

[[ 1. -1.]
 [-2.  3.]]


In [6]:
x = inversa_A.dot(b)
print(x)

[[0.]
 [1.]]


In [7]:
print(A.dot(x))

[[1.]
 [1.]]


In [8]:
sol_2 = inversa_A.dot(np.array([[3],[7]]))
print(sol_2)

[[-4.]
 [15.]]


In [9]:
print(A.dot(sol_2))

[[3.]
 [7.]]


In [4]:
#sistema de ecuaciones
# y -7x = 2
# y -3x = 5
A = np.array([[1, -7], [1,-3]])
b = np.array([[2],[5]])
inversa_A = np.linalg.inv(A)
print(inversa_A)

[[-0.75  1.75]
 [-0.25  0.25]]


In [5]:
x = inversa_A.dot(b)
print(x)

[[7.25]
 [0.75]]
